In [6]:
import numpy as np

def test(a):
    ans1=a+1
    ans2=a+2
    return ans1,ans2

left,right=test(np.arange(4))
print(left)
print(right)

[1 2 3 4]
[2 3 4 5]


In [21]:
a=np.zeros((0,1),dtype=object)
b=np.append(a,'apple')
print(b)

['apple']


In [18]:
a=[1,1,1,1,1]
b=np.argmax(a)
print(b)

0


In [20]:
x = np.array([1, 2, 3, 4])
print(x.shape)
y=x.reshape((4,1))
print(y)

(4,)
[[1]
 [2]
 [3]
 [4]]


In [32]:
a=np.zeros((3,4))
i=1
b=a[:,[0]]
print(type(b))


<class 'numpy.ndarray'>
